<?php
require_once 'config.php';
require_once 'functions.php';
require_once 'error_tracker.php';

$date = getTradingDate();

// $companies = [
//     'FICO' => 'Fair Isaac',
//     'FIS' => 'Fidelity National Information Services',
//     'FITB' => 'Fifth Third Bank',
//     'FMC' => 'FMC Corporation',
//     'FOX' => 'Fox Corporation (Class B)',
//     'FOXA' => 'Fox Corporation (Class A)',
//     'FRT' => 'Federal Realty',
//     'FSLR' => 'First Solar',
//     'FTNT' => 'Fortinet',
//     'FTV' => 'Fortive',
//     'GD' => 'General Dynamics',
//     'GE' => 'GE Aerospace',
//     'GEHC' => 'GE HealthCare',
//     'GEN' => 'Gen Digital',
//     'GEV' => 'GE Vernova',
//     'GILD' => 'Gilead Sciences',
//     'GIS' => 'General Mills',
//     'GL' => 'Globe Life',
//     'GLW' => 'Corning Inc.',
//     'GM' => 'General Motors',
//     'GNRC' => 'Generac',
//     'GOOG' => 'Alphabet Inc. (Class C)',
//     'GOOGL' => 'Alphabet Inc. (Class A)',
//     'GPC' => 'Genuine Parts Company',
//     'GPN' => 'Global Payments',
//     'GRMN' => 'Garmin',
//     'GS' => 'Goldman Sachs',
//     'GWW' => 'W. W. Grainger',
//     'HAL' => 'Halliburton',
//     'HAS' => 'Hasbro',
//     'HBAN' => 'Huntington Bancshares',
//     'HCA' => 'HCA Healthcare',
//     'HD' => 'Home Depot (The)',
//     // 'HES' => 'Hess Corporation',
//     'HIG' => 'Hartford (The)',
//     'HII' => 'Huntington Ingalls Industries',
//     'HLT' => 'Hilton Worldwide',
//     'HOLX' => 'Hologic',
//     'HON' => 'Honeywell',
//     'HPE' => 'Hewlett Packard Enterprise',
//     'HPQ' => 'HP Inc.',
//     'HRL' => 'Hormel Foods',
//     'HSIC' => 'Henry Schein',
//     'HST' => 'Host Hotels & Resorts',
//     'HSY' => 'Hershey\'s',
//     'HUBB' => 'Hubbell Incorporated',
//     'HUM' => 'Humana',
//     'HWM' => 'Howmet Aerospace',
//     'IBM' => 'IBM',
//     'ICE' => 'Intercontinental Exchange',
//     'IDXX' => 'Idexx Laboratories',
//     'IEX' => 'IDEX Corporation',
//     'IFF' => 'International Flavors & Fragrances',
//     'ILMN' => 'Illumina',
//     'INCY' => 'Incyte',
//     'INTC' => 'Intel',
//     'INTU' => 'Intuit',
//     'INVH' => 'Invitation Homes',
//     'IP' => 'International Paper',
//     // 'IPG' => 'Interpublic Group of Companies (The)',
//     'IQV' => 'IQVIA',
//     'IR' => 'Ingersoll Rand',
//     'IRM' => 'Iron Mountain',
//     'ISRG' => 'Intuitive Surgical',
//     'IT' => 'Gartner',
//     'ITW' => 'Illinois Tool Works',
//     'IVZ' => 'Invesco',
//     'J' => 'Jacobs Solutions',
//     'JBHT' => 'J.B. Hunt',
//     'JBL' => 'Jabil',
//     'JCI' => 'Johnson Controls',
//     'JKHY' => 'Jack Henry & Associates',
//     'JNJ' => 'Johnson & Johnson',
//     // 'JNPR' => 'Juniper Networks',
//     'JPM' => 'JPMorgan Chase',
//     'K' => 'Kellanova',
//     'KDP' => 'Keurig Dr Pepper',
//     'KEY' => 'KeyCorp',
//     'KEYS' => 'Keysight',
//     'KHC' => 'Kraft Heinz',
//     'KIM' => 'Kimco Realty',
//     'KLAC' => 'KLA Corporation',
//     'KMB' => 'Kimberly-Clark',
//     'KMI' => 'Kinder Morgan',
//     'KMX' => 'CarMax',
//     'KO' => 'Coca-Cola Company (The)',
//     'KR' => 'Kroger',
//     'KVUE' => 'Kenvue',
//     'L' => 'Loews Corporation',
//     'LDOS' => 'Leidos',
//     'LEN' => 'Lennar',
//     'LH' => 'LabCorp',
//     'LHX' => 'L3Harris',
//     'LIN' => 'Linde plc',
//     'LKQ' => 'LKQ Corporation',
//     'LLY' => 'Eli Lilly and Company',
//     'LMT' => 'Lockheed Martin',
//     'LNT' => 'Alliant Energy',
//     'LOW' => 'Lowe\'s',
//     'LRCX' => 'Lam Research',
//     'LULU' => 'Lululemon Athletica',
//     'LUV' => 'Southwest Airlines',
//     'LVS' => 'Las Vegas Sands',
//     'LW' => 'Lamb Weston',
//     'LYB' => 'LyondellBasell',
//     'LYV' => 'Live Nation Entertainment'
// ];

$con = getDbConnection();
$errorTracker = new ErrorTracker($con, __FILE__);
$companies = getCompaniesChunk($con, 2);

processCompanies($companies, $con, $errorTracker, $date);

// Errors are now saved to database only - no email sending from stock scripts
// Email will be sent by nightly script (send_stock_error_email.php)

$con->close();
?>
