<?php
require_once 'config.php';
require_once 'functions.php';
require_once 'error_tracker.php';

$date = getTradingDate();

// $companies = [
//     'QCOM' => 'Qualcomm',
//     'QRVO' => 'Qorvo',
//     'RCL' => 'Royal Caribbean Group',
//     'REG' => 'Regency Centers',
//     'REGN' => 'Regeneron',
//     'RF' => 'Regions Financial Corporation',
//     'RHI' => 'Robert Half',
//     'RJF' => 'Raymond James',
//     'RL' => 'Ralph Lauren Corporation',
//     'RMD' => 'ResMed',
//     'ROK' => 'Rockwell Automation',
//     'ROL' => 'Rollins, Inc.',
//     'ROP' => 'Roper Technologies',
//     'ROST' => 'Ross Stores',
//     'RSG' => 'Republic Services',
//     'RTX' => 'RTX Corporation',
//     'RVTY' => 'Revvity',
//     'SBAC' => 'SBA Communications',
//     'SBUX' => 'Starbucks',
//     'SCHW' => 'Charles Schwab Corporation',
//     'SHW' => 'Sherwin-Williams',
//     'SJM' => 'J.M. Smucker Company (The)',
//     'SLB' => 'Schlumberger',
//     'SMCI' => 'Supermicro',
//     'SNA' => 'Snap-on',
//     'SNPS' => 'Synopsys',
//     'SO' => 'Southern Company',
//     'SOLV' => 'Solventum',
//     'SPG' => 'Simon Property Group',
//     'SPGI' => 'S&P Global',
//     'SRE' => 'Sempra Energy',
//     'STE' => 'Steris',
//     'STLD' => 'Steel Dynamics',
//     'STT' => 'State Street Corporation',
//     'STX' => 'Seagate Technology',
//     'STZ' => 'Constellation Brands',
//     'SWK' => 'Stanley Black & Decker',
//     'SWKS' => 'Skyworks Solutions',
//     'SYF' => 'Synchrony Financial',
//     'SYK' => 'Stryker Corporation',
//     'SYY' => 'Sysco',
//     'T' => 'AT&T',
//     'TAP' => 'Molson Coors Beverage Company',
//     'TDG' => 'TransDigm Group',
//     'TDY' => 'Teledyne Technologies',
//     'TECH' => 'Bio-Techne',
//     'TEL' => 'TE Connectivity',
//     'TER' => 'Teradyne',
//     'TFC' => 'Truist',
//     'TFX' => 'Teleflex',
//     'TGT' => 'Target Corporation',
//     'TJX' => 'TJX Companies',
//     'TMO' => 'Thermo Fisher Scientific',
//     'TMUS' => 'T-Mobile US',
//     'TPR' => 'Tapestry, Inc.',
//     'TRGP' => 'Targa Resources',
//     'TRMB' => 'Trimble Inc.',
//     'TROW' => 'T. Rowe Price',
//     'TRV' => 'Travelers Companies (The)',
//     'TSCO' => 'Tractor Supply',
//     'TSLA' => 'Tesla, Inc.',
//     'TSN' => 'Tyson Foods',
//     'TT' => 'Trane Technologies',
//     'TTWO' => 'Take-Two Interactive',
//     'TXN' => 'Texas Instruments',
//     'TXT' => 'Textron',
//     'TYL' => 'Tyler Technologies',
//     'UAL' => 'United Airlines Holdings',
//     'UBER' => 'Uber',
//     'UDR' => 'UDR, Inc.',
//     'UHS' => 'Universal Health Services',
//     'ULTA' => 'Ulta Beauty',
//     'UNH' => 'UnitedHealth Group',
//     'UNP' => 'Union Pacific Corporation',
//     'UPS' => 'United Parcel Service',
//     'URI' => 'United Rentals',
//     'USB' => 'U.S. Bank',
//     'V' => 'Visa Inc.',
//     'VICI' => 'Vici Properties',
//     'VLO' => 'Valero Energy',
//     'VLTO' => 'Veralto',
//     'VMC' => 'Vulcan Materials Company',
//     'VRSK' => 'Verisk',
//     'VRSN' => 'Verisign',
//     'VRTX' => 'Vertex Pharmaceuticals',
//     'VST' => 'Vistra',
//     'VTR' => 'Ventas',
//     'VTRS' => 'Viatris',
//     'VZ' => 'Verizon',
//     'WAB' => 'Wabtec',
//     'WAT' => 'Waters Corporation',
//     // 'WBA' => 'Walgreens Boots Alliance',
//     'WBD' => 'Warner Bros. Discovery',
//     'WDC' => 'Western Digital',
//     'WEC' => 'WEC Energy Group',
//     'WELL' => 'Welltower',
//     'WFC' => 'Wells Fargo',
//     'WM' => 'Waste Management',
//     'WMB' => 'Williams Companies',
//     'WMT' => 'Walmart',
//     'WRB' => 'W. R. Berkley Corporation',
//     // 'WRK' => 'WestRock',
//     'WST' => 'West Pharmaceutical Services',
//     'WTW' => 'Willis Towers Watson',
//     'WY' => 'Weyerhaeuser',
//     'WYNN' => 'Wynn Resorts',
//     'XEL' => 'Xcel Energy',
//     'XOM' => 'ExxonMobil',
//     'XYL' => 'Xylem Inc.',
//     'YUM' => 'Yum! Brands',
//     'ZBH' => 'Zimmer Biomet',
//     'ZBRA' => 'Zebra Technologies',
//     'ZTS' => 'Zoetis'
// ];

$con = getDbConnection();
$errorTracker = new ErrorTracker($con, __FILE__);
$companies = getCompaniesChunk($con, 4);
// print_r($companies);exit;
processCompanies($companies, $con, $errorTracker, $date);

// Errors are now saved to database only - no email sending from stock scripts
// Email will be sent by nightly script (send_stock_error_email.php)

$con->close();
?>
